version: '3.2'
services:
  legacywebshop:
    build:
      context: ./legacy
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    build:
      context: ./legacy
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql_7"
      - ./legacy/sql/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

  category-microservice:
    build:
      context: ./category
      dockerfile: ./Dockerfile
    depends_on:
      - web-shop-db-image
    ports:
      - "8081:8081"
    networks:
      local_dev_net:
          aliases:
              - category-microservice
  
  product-microservice:
    build:
      context: ./product
      dockerfile: ./Dockerfile
    depends_on:
      - web-shop-db-image
    ports:
      - "8082:8082"
    networks:
      local_dev_net:
          aliases:
              - product-microservice
  
  user-microservice:
    build:
      context: ./user
      dockerfile: ./Dockerfile
    depends_on:
      - web-shop-db-image
    ports:
      - "8083:8083"
    networks:
      local_dev_net:
          aliases:
              - user-microservice

networks:
  local_dev_net:
    driver: bridge
